import { Entity, Column, ManyToOne, JoinColumn } from 'typeorm';
import { BaseEntity } from '@/common/entities/base.entity';
import { User } from '@/modules/auth/entities/user.entity';

@Entity('coupons')
export class Coupon extends BaseEntity {
  @Column({ unique: true })
  code: string;

  @Column()
  name: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  @Column()
  type: string; // percentage, fixed_amount, free_shipping, buy_x_get_y

  @Column({ type: 'simple-json' })
  discountValue: {
    type: string; // percentage, fixed_amount
    value: number;
    maxDiscountAmount?: number; // For percentage coupons
    freeShipping?: boolean;
    buyQuantity?: number; // For buy_x_get_y
    getQuantity?: number; // For buy_x_get_y
  };

  @Column({ type: 'simple-json', nullable: true })
  conditions: {
    minOrderValue?: number;
    maxOrderValue?: number;
    applicableProducts?: string[]; // Product IDs
    applicableCategories?: string[]; // Category IDs
    applicableVendors?: string[]; // Vendor IDs
    excludedProducts?: string[];
    newCustomersOnly?: boolean;
    firstOrderOnly?: boolean;
    specificCustomers?: string[]; // User IDs
    paymentMethods?: string[];
    shippingMethods?: string[];
  };

  @Column({ type: 'timestamp' })
  validFrom: Date;

  @Column({ type: 'timestamp' })
  validUntil: Date;

  @Column({ default: true })
  isActive: boolean;

  @Column({ type: 'int', nullable: true })
  usageLimit: number; // Total usage limit

  @Column({ type: 'int', default: 1 })
  usageLimitPerCustomer: number;

  @Column({ type: 'int', default: 0 })
  usageCount: number;

  @Column({ type: 'simple-json', default: {} })
  usageHistory: Record<string, {
    customerId: string;
    orderId: string;
    usedAt: string;
    discountAmount: number;
  }[]>;

  @Column({ type: 'simple-json', nullable: true })
  generation: {
    isAutoGenerated: boolean;
    batchId?: string;
    prefix?: string;
    length?: number;
    pattern?: string; // RANDOM, SEQUENTIAL, CUSTOM
  };

  @Column({ type: 'simple-json', nullable: true })
  distribution: {
    channels: string[]; // email, sms, social_media, referral
    targetAudience: string[]; // new_customers, vip_customers, abandoned_cart
    scheduledSendDate?: string;
    personalizedMessage?: string;
  };

  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  totalDiscountGiven: number;

  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  revenueGenerated: number;

  @Column({ type: 'simple-json', nullable: true })
  analytics: {
    impressions: number;
    redemptions: number;
    redemptionRate: number;
    avgOrderValue: number;
    totalSavings: number;
    conversionRate: number;
  };

  @ManyToOne(() => User)
  @JoinColumn({ name: 'createdById' })
  createdBy: User;

  @Column()
  createdById: string;

  @Column({ type: 'simple-array', nullable: true })
  tags: string[];

  @Column({ type: 'text', nullable: true })
  notes: string;
}