import apiClient from './client';

// Backend POJO imports - Marketing Module
interface CouponDto {
  id: string;
  code: string;
  name: string;
  description?: string;
  type: string; // percentage, fixed_amount, free_shipping, buy_x_get_y
  discountValue: {
    type: string; // percentage, fixed_amount
    value: number;
    maxDiscountAmount?: number;
    freeShipping?: boolean;
    buyQuantity?: number;
    getQuantity?: number;
  };
  conditions?: {
    minOrderValue?: number;
    maxOrderValue?: number;
    applicableProducts?: string[];
    applicableCategories?: string[];
    applicableVendors?: string[];
    excludedProducts?: string[];
    newCustomersOnly?: boolean;
    firstOrderOnly?: boolean;
    specificCustomers?: string[];
    paymentMethods?: string[];
    shippingMethods?: string[];
  };
  validFrom: Date;
  validUntil: Date;
  isActive: boolean;
  usageLimit?: number;
  usageLimitPerCustomer: number;
  usageCount: number;
  usageHistory: Record<string, {
    customerId: string;
    orderId: string;
    usedAt: string;
    discountAmount: number;
  }[]>;
  generation?: {
    isAutoGenerated: boolean;
    batchId?: string;
    prefix?: string;
    length?: number;
    pattern?: string;
  };
  distribution?: {
    channels: string[];
    targetAudience: string[];
    scheduledSendDate?: string;
    personalizedMessage?: string;
  };
  totalDiscountGiven: number;
  revenueGenerated: number;
  analytics?: {
    impressions: number;
    redemptions: number;
    redemptionRate: number;
    avgOrderValue: number;
    totalSavings: number;
    conversionRate: number;
  };
  createdById: string;
  tags?: string[];
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

// API Response wrappers
interface CouponsAPIResponse<T> {
  success: boolean;
  data: T;
  message?: string;
}

interface PaginatedCouponsResponse<T> {
  success: boolean;
  data: {
    items: T[];
    total: number;
    page: number;
    totalPages: number;
    hasNext: boolean;
    hasPrev: boolean;
  };
}

// Request types
export interface CreateCouponRequest {
  code: string;
  name: string;
  description?: string;
  type: string;
  discountValue: {
    type: string;
    value: number;
    maxDiscountAmount?: number;
    freeShipping?: boolean;
    buyQuantity?: number;
    getQuantity?: number;
  };
  conditions?: {
    minOrderValue?: number;
    maxOrderValue?: number;
    applicableProducts?: string[];
    applicableCategories?: string[];
    applicableVendors?: string[];
    excludedProducts?: string[];
    newCustomersOnly?: boolean;
    firstOrderOnly?: boolean;
    specificCustomers?: string[];
    paymentMethods?: string[];
    shippingMethods?: string[];
  };
  validFrom: string;
  validUntil: string;
  usageLimit?: number;
  usageLimitPerCustomer?: number;
  generation?: {
    isAutoGenerated: boolean;
    batchId?: string;
    prefix?: string;
    length?: number;
    pattern?: string;
  };
  distribution?: {
    channels: string[];
    targetAudience: string[];
    scheduledSendDate?: string;
    personalizedMessage?: string;
  };
  tags?: string[];
  notes?: string;
}

export interface UpdateCouponRequest extends Partial<CreateCouponRequest> {
  isActive?: boolean;
}

export interface GetCouponsResponse {
  coupons: CouponDto[];
  total: number;
  page: number;
  totalPages: number;
}

// Legacy interfaces for backward compatibility
export interface Coupon {
  id: number;
  code: string;
  type: 'percentage' | 'fixed' | 'free-shipping' | 'buy-x-get-y';
  value: number;
  minPurchase?: number;
  maxDiscount?: number;
  description: string;
  startDate: string;
  endDate: string;
  usageLimit: number;
  usageCount: number;
  perUserLimit: number;
  userUsageCount: number;
  status: 'active' | 'expired' | 'upcoming' | 'used-up';
  categories?: string[];
  excludedProducts?: number[];
  stackable: boolean;
  autoApply: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateCouponDto {
  code: string;
  type: 'percentage' | 'fixed' | 'free-shipping' | 'buy-x-get-y';
  value: number;
  minPurchase?: number;
  maxDiscount?: number;
  description: string;
  startDate: string;
  endDate: string;
  usageLimit: number;
  perUserLimit: number;
  categories?: string[];
  excludedProducts?: number[];
  stackable: boolean;
  autoApply: boolean;
}

export interface UpdateCouponDto extends Partial<CreateCouponDto> {
  status?: 'active' | 'expired' | 'upcoming' | 'used-up';
}

export interface CouponFilters {
  status?: 'active' | 'expired' | 'upcoming' | 'used-up';
  type?: 'percentage' | 'fixed' | 'free-shipping' | 'buy-x-get-y';
  search?: string;
  page?: number;
  limit?: number;
}

export interface CouponStats {
  total: number;
  active: number;
  expired: number;
  upcoming: number;
  usedUp: number;
  totalUsage: number;
  totalDiscountGiven: number;
  avgUsagePerCoupon: number;
}

export interface CouponUsage {
  id: number;
  couponId: number;
  couponCode: string;
  userId: number;
  userName: string;
  orderId: number;
  discountAmount: number;
  usedAt: string;
}

export interface ValidateCouponDto {
  code: string;
  userId?: number;
  cartTotal: number;
  items?: Array<{
    productId: number;
    categoryId: number;
    quantity: number;
    price: number;
  }>;
}

export interface CouponValidation {
  valid: boolean;
  coupon?: Coupon;
  discountAmount?: number;
  message?: string;
  errors?: string[];
}

export const couponsAPI = {
  // Get all coupons with filters
  getAll: async (filters?: CouponFilters): Promise<GetCouponsResponse> => {
    const response = await apiClient.get<PaginatedCouponsResponse<CouponDto>>('/coupons', { params: filters });
    return {
      coupons: response.data.data.items,
      total: response.data.data.total,
      page: response.data.data.page,
      totalPages: response.data.data.totalPages
    };
  },

  // Get coupon by ID
  getById: async (id: number): Promise<CouponDto> => {
    const response = await apiClient.get<CouponsAPIResponse<CouponDto>>(`/coupons/${id}`);
    return response.data.data;
  },

  // Get coupon by code
  getByCode: async (code: string): Promise<CouponDto> => {
    const response = await apiClient.get<CouponsAPIResponse<CouponDto>>(`/coupons/code/${code}`);
    return response.data.data;
  },

  // Create new coupon
  create: async (data: CreateCouponRequest): Promise<CouponDto> => {
    const response = await apiClient.post<CouponsAPIResponse<CouponDto>>('/coupons', data);
    return response.data.data;
  },

  // Update coupon
  update: async (id: number, data: UpdateCouponRequest): Promise<CouponDto> => {
    const response = await apiClient.put<CouponsAPIResponse<CouponDto>>(`/coupons/${id}`, data);
    return response.data.data;
  },

  // Delete coupon
  delete: async (id: number): Promise<void> => {
    await apiClient.delete(`/coupons/${id}`);
  },

  // Get coupon statistics
  getStats: async (): Promise<CouponStats> => {
    const response = await apiClient.get<CouponsAPIResponse<CouponStats>>('/coupons/stats');
    return response.data.data;
  },

  // Get coupon usage history
  getUsageHistory: async (couponId: number, page = 1, limit = 10): Promise<{
    usage: CouponUsage[];
    total: number;
    page: number;
    limit: number;
  }> => {
    const response = await apiClient.get<PaginatedCouponsResponse<CouponUsage>>(`/coupons/${couponId}/usage`, {
      params: { page, limit },
    });
    return {
      usage: response.data.data.items,
      total: response.data.data.total,
      page: response.data.data.page,
      limit: limit
    };
  },

  // Validate coupon
  validate: async (data: ValidateCouponDto): Promise<CouponValidation> => {
    const response = await apiClient.post<CouponsAPIResponse<CouponValidation>>('/coupons/validate', data);
    return response.data.data;
  },

  // Apply coupon to cart
  apply: async (code: string, userId: number, cartTotal: number): Promise<any> => {
    const response = await apiClient.post<CouponsAPIResponse<any>>('/coupons/apply', {
      code,
      userId,
      cartTotal,
    });
    return response.data.data;
  },

  // Deactivate coupon
  deactivate: async (id: number): Promise<CouponDto> => {
    const response = await apiClient.patch<CouponsAPIResponse<CouponDto>>(`/coupons/${id}/deactivate`);
    return response.data.data;
  },

  // Activate coupon
  activate: async (id: number): Promise<CouponDto> => {
    const response = await apiClient.patch<CouponsAPIResponse<CouponDto>>(`/coupons/${id}/activate`);
    return response.data.data;
  },

  // Duplicate coupon
  duplicate: async (id: number): Promise<CouponDto> => {
    const response = await apiClient.post<CouponsAPIResponse<CouponDto>>(`/coupons/${id}/duplicate`);
    return response.data.data;
  },

  // Get auto-apply coupons
  getAutoApply: async (cartTotal: number, items?: any[]): Promise<CouponDto[]> => {
    const response = await apiClient.post<CouponsAPIResponse<CouponDto[]>>('/coupons/auto-apply', {
      cartTotal,
      items,
    });
    return response.data.data;
  },

  // Bulk delete coupons
  bulkDelete: async (ids: number[]): Promise<any> => {
    const response = await apiClient.post<CouponsAPIResponse<any>>('/coupons/bulk-delete', { ids });
    return response.data.data;
  },

  // Bulk update status
  bulkUpdateStatus: async (ids: number[], status: 'active' | 'expired' | 'upcoming' | 'used-up'): Promise<any> => {
    const response = await apiClient.post<CouponsAPIResponse<any>>('/coupons/bulk-update-status', {
      ids,
      status,
    });
    return response.data.data;
  },
};
